### ISSUE TITLE
优化界面，当前显示有些乱

### ISSUE THREAD

**Issue by zm60** [cloudenergy/web#2]
![image](https://cloud.githubusercontent.com/assets/14212067/20565601/2125e396-b1cd-11e6-9d90-e25513a5978e.png)

**Comment by jQChou** [comment]
committed and pushed to release

**Comment by realmx** [comment]
Issue moved to [cloudenergy/web-source #21](https://github.com/cloudenergy/web-source/issues/21) via [**ZenHub**](https://www.zenhub.com/)
